{{- include "fixter-collector.validate" . }}
{{- if not .Values.fixter.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fixter-collector.fullname" . }}
  labels:
    {{- include "fixter-collector.labels" . | nindent 4 }}
type: Opaque
stringData:
  FIXTER_API_KEY: {{ .Values.fixter.apiKey | quote }}
{{- end }}
